### ISSUE TITLE
Unable to start server machine

### ISSUE THREAD

**Issue by teterkin** [eoli3n/vagrant-pxe#1]
Hi!
I am trying to vagrant up server machine, It creates it, but it cannot connect to it via ssh:
`==> pxe_server: Waiting for machine to boot. This may take a few minutes...
    pxe_server: SSH address: 127.0.0.1:2222
    pxe_server: SSH username: root
    pxe_server: SSH auth method: private key
    pxe_server: Warning: Authentication failure. Retrying...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'unknown' state. Please verify everything is configured
properly and try again.`
Also if I issue vagrant ssh it cannot login:
`>vagrant ssh
Permission denied (publickey).`
I can login via Virtualbox with vagrant/vagrant login and password.

**Comment by eoli3n** [comment]
In the README.md

```
Vagrant will hang on Warning: Connection refused. Retrying... error. That's because we edited network configuration to enable pxeboot. Please ignore it.

Virtualbox gui will pop up, showing vm netboot.
```

The reason is that the vm doesn't have the vagrant administration interface. It was required to create a new local network, to enable pxe boot. ( vagrant default admin interface has a DHCP... so two DHCP on the same network doesn't work as expected)

**Comment by teterkin** [comment]
Thank you for the answer. So far nothing popes up. 
I will try to start client machine. Thank you!

**Comment by eoli3n** [comment]
Maybe something changed with an update, i will try and tell you more soon.

**Comment by eoli3n** [comment]
Fixed, please try

**Comment by teterkin** [comment]
Thanks, it works now!
By the way is it intentional for client machine to boot over network first and then, in 10 seconds, to boot to hard disk?

**Comment by eoli3n** [comment]
it is. The default boot file that tftp gives, asks the client to local boot.
The file is https://github.com/eoli3n/vagrant-pxe/blob/master/server/config/ressources/pxelinux.cfg/default
If you want to boot something else, you can edit that file or create a IP specific file
see : http://www.syslinux.org/wiki/index.php?title=PXELINUX
